// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		double underMid = 0;
		double overMid = 0;
		double ratio = 1;
	    for ( int i = 0 ; i < n ; i++ ) {
			// System.out.println(">0.5");
			if (Math.random() < 0.5) underMid += 1; else overMid +=1;
				// underMid += 1;}
			// else {
				// overMid +=1;}
		if (overMid>underMid) ratio = underMid/overMid;  
		else if (underMid > overMid) ratio = overMid/underMid;}
		
		System.out.println(">0.5: " + underMid);
		System.out.println("<=0.5: " + overMid);
		System.out.println("Ratio: " + ratio);
		}
	}

